name: CICD

on: 
  workflow_call:
    inputs:
      org:
        required: true
        type: string
      imageName:
        required: true
        type: string
    
    secrets:
      registry:
        required: false
      username:
        required: false
      password:
        required: false

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build
        run: |
          docker build -t ${ inputs.org }/${ inputs.imageName }:${{ github.sha }} .
          docker push ${ inputs.org }/${ inputs.imageName }:${{ github.sha }}

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${ inputs.org }/${ inputs.imageName }:${{ github.sha }} ${ inputs.org }/${ inputs.imageName }:latest
          docker push ${ inputs.org }/${ inputs.imageName }
