name: CICD

# Build and publish a docker image.
# Requires at least an org and image name to work correctly.
# Usage:
#
# jobs:
#   build:
#     uses: homebots/workflows/.github/workflows/docker-build-and-push.yml@master
#     with:
#       org: 'taco'
#       imageName: 'cats'

on:
  workflow_call:
    inputs:
      org:
        required: true
        type: string
      imageName:
        required: true
        type: string
      registry:
        required: false
        type: string
      defaultBranch:
        required: false
        type: string
        default: main
    secrets:
      username:
        required: false
      password:
        required: false

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-18.04

    env:
      TAG: ${{ inputs.org }}/${{ inputs.imageName }}:${{ github.sha }}
      LATEST_TAG: ${{ inputs.org }}/${{ inputs.imageName }}:latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build branch
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build latest
        if: github.ref == 'refs/heads/${{ inputs.defaultBranch }}'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
