name: CICD

# Build and publish a docker image.
# Requires at least an org and image name to work correctly.
# Usage:
#
# jobs:
#   build:
#     uses: homebots/workflows/.github/workflows/docker-build-and-push.yml@master
#     with:
#       org: 'taco'
#       imageName: 'cats'

on: 
  workflow_call:
    inputs:
      org:
        required: true
        type: string
      imageName:
        required: true
        type: string
      registry:
        required: false
      username:
        required: false
      password:
        required: false
      defaultBranch:
        required: false
        default: main

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }} 
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Build
        run: |
          docker build -t ${{ inputs.org }}/${{ inputs.imageName }}:${{ github.sha }} .
          docker push ${{ inputs.org }}/${{ inputs.imageName }}:${{ github.sha }}

      - name: Publish
        if: github.ref == 'refs/heads/${{ inputs.defaultBranch }}'
        run: |
          docker tag ${{ inputs.org }}/${{ inputs.imageName }}:${{ github.sha }} ${{ inputs.org }}/${{ inputs.imageName }}:latest
          docker push ${{ inputs.org }}/${{ inputs.imageName }}
