name: Build/Release

on:
  workflow_call:
    inputs:
      branches:
        required: false
      build:
        required: false
        default: true
        type: boolean
    secrets:
      NPM_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true
      
jobs:
  build:
    name: Build/Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies and build library
        if: inputs.build == 'true'
        run: npm ci && npm run test && npm run build

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with: 
          branches: ${{ inputs.branches }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - runs: echo Release ${{ steps.release.outputs.new_release_version }}
      - runs: echo ${{ steps.release.outputs.new_release_notes }}