name: Build/Release

on:
  workflow_call:
    inputs:
      build:
        required: false
        default: true
        type: boolean
      distPath:
        required: false
        default: dist
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true
      
jobs:
  build:
    name: Build
    if: inputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies and build library
        run: npm ci && npm run test && npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ inputs.distPath }}

  release:
    needs: build
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        if: inputs.build == 'true'
        uses: actions/download-artifact@v2
        with:
          name: dist
      - uses: cycjimmy/semantic-release-action@v2.5.0
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
