name: Build/Release

on:
  workflow_call:
    inputs:
      branches:
        required: false
        type: string
      build:
        required: false
        default: true
        type: boolean
      path:
        required: false
        default: '.'
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GH_TOKEN:
        required: true
      
jobs:
  build:
    name: Build/Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: cd ${{ inputs.path }}
      - name: Install dependencies and build library
        if: inputs.build
        run: npm ci && npm run test && npm run build

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v3.0.0
        with: 
          branches: ${{ inputs.branches }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
