name: Build/Release

# Automate releases to a NPM-compatible registry
#
# Usage:
#    name: CICD
#    on:
#      push:
#
#    jobs:
#      release:
#        uses: homebots/workflows/.github/workflows/node-build-release.yml@master
#        branches: main
#        build: true
#        path: '.'
#        registry: ''
#        secrets:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      branches:
        required: false
        default: main
        type: string
      build:
        required: false
        default: true
        type: boolean
      path:
        required: false
        default: "."
        type: string
      registry:
        required: false
        default: ""
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GH_TOKEN:
        required: true

jobs:
  build:
    name: Build/Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Install dependencies and build library
        if: inputs.build
        run: npm i && npm run test && npm run build

      - name: Set publish registry
        if: inputs.registry
        run: |
          echo "registry=${{ inputs.registry }}" >> .npmrc
          cat .npmrc

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.4.2
        with:
          branches: ${{ inputs.branches }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
